[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sagikazarmark/szamlazz-rs"
authors = ["Márk Sági-Kazár <mark.sagikazar@gmail.com>"]
keywords = ["szamlazz", "invoice", "billing", "hungary"]
categories = ["api-bindings"]

[workspace.dependencies]
szamlazz-adatkapcsolat = { path = "crates/szamlazz-adatkapcsolat", version = "0.1.0" }
szamlazz-agent = { path = "crates/szamlazz-agent", version = "0.1.0" }
szamlazz-ipn = { path = "crates/szamlazz-ipn", version = "0.1.0" }

axum = { version = "0.8.9", default-features = false }
base64 = "0.23.1"
http = "1.4.2"
http-body-util = "0.1.3"
jiff = { version = "0.2.31", default-features = false, features = ["std", "serde"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
rust_decimal = { version = "1.42.1", features = ["serde", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.3", default-features = false }
tower = "0.5.3"

[workspace.lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs)'] }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"

[workspace.metadata.release]
sign-commit = true
sign-tag = true
shared-version = true
tag-message = "Release {{version}}"
tag-name = "v{{version}}"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
