ignore = [".devenv", "target"]

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"

settings.rustVersion = "1.97-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

settings.lock = '"PINNED"'
