<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlnyugtasendvalasz" xmlns:tns="http://www.szamlazz.hu/xmlnyugtasendvalasz" elementFormDefault="qualified">

    <element name="xmlnyugtasendvalasz">
        <complexType>
            <all>
                <element name="sikeres"           type="boolean"               maxOccurs="1" minOccurs="1"></element>
                <element name="hibakod"           type="int"                   maxOccurs="1" minOccurs="0"></element>
                <element name="hibauzenet"        type="string"                maxOccurs="1" minOccurs="0"></element>
            </all>
        </complexType>
    </element>
</schema>
